version: '3.8'

services:
  perf-mirror:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # Persist the SQLite database
      - perf_mirror_data:/app/prisma
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./dev.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/categories", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  perf_mirror_data:
    driver: local 