# fly.toml app configuration file generated for perf-mirror-rough-water-776 on 2025-06-11T22:49:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'perf-mirror-rough-water-776'
primary_region = 'sjc'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[env]
  DATABASE_URL = 'file:/data/perf-mirror.db'
  NODE_ENV = 'production'

[[mounts]]
  source = 'perf_mirror_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
